<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="lysander">

  <xacro:include filename="$(find motor_controller)/urdf/wheel.urdf.xacro" />

  <xacro:property name="body_height" value="0.0508" />
  <xacro:property name="body_length" value="0.3048" />
  <xacro:property name="body_width" value="0.2286" />
  <xacro:property name="fwheel_offset" value="-0.13" />
  <xacro:property name="wheel_forward_of_center_distance" value=".0762" />
  <xacro:property name="motor_height" value="0.0254" />
  <xacro:property name="scanner_height" value="0.015" />
  <xacro:property name="scanner_length" value="0.045" />
  <xacro:property name="scanner_width" value="0.015" />
  <xacro:property name="wheel_radius" value="0.06" />
  <xacro:property name="wheel_spacer" value="0.00254" />
  <xacro:property name="wheel_width" value="0.060" />
  <xacro:property name="body_center_height" value="${wheel_radius+(motor_height/2)+(body_height/2)}" />

  <xacro:property name="scanner_x_offset" value="${(body_length/2)-(scanner_width/2)}" />
  <xacro:property name="scanner_z_offset" value="${body_center_height+(body_height/2)+(scanner_height/2)+.00508}" />

  <material name="base">
    <color rgba="0.25 0.25 0.53 1" />>
  </material>

  <material name="wheel">
    <color rgba="0.6 0.5 0.5 1" />
  </material>

  <!--xacro:include filename="$(find m1)/robots/m1.gazebo" /-->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>
  
  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <gazebo reference="scanner">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!--gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller">
      <alwaysOn>true</alwaysOn>
      <commandTopic>cmd_vel</commandTopic>
      <leftJoint>base_to_lwheel_joint</leftJoint>
      <legacyMode>false</legacyMode>
      <odometryFrame>odom</odometryFrame>
      <odometryTopic>odom</odometryTopic>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>false</publishWheelJointState>
      <publishWheelTF>true</publishWheelTF>
      <rightJoint>base_to_rwheel_joint</rightJoint>
      <robotBaseFrame>base_link</robotBaseFrame>
      <rosDebugLevel>Debug</rosDebugLevel>
      <torque>0.1</torque>
      <updateRate>20</updateRate>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <wheelSeparation>${body_width+(2*wheel_spacer)+wheel_width}</wheelSeparation>
    </plugin>
  </gazebo-->

  <!-- Parts -->
  <link name="base_link">
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} 0.0508"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${body_center_height}"/>
    </collision>
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} 0.0508"/>
      </geometry>
      <material name="base" />
      <origin rpy="0 0 0" xyz="0 0 ${body_center_height}"/>
    </visual>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1" />
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
    </inertial>
  </link>
  
  <xacro:wheel wheel_prefix="front_left" is_caster="false" >
    <origin xyz="${wheel_forward_of_center_distance} ${(body_width/2)+wheel_spacer+(wheel_width/2)} ${wheel_radius}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="front_right" is_caster="false" >
    <origin xyz="${wheel_forward_of_center_distance} -${(body_width/2)+wheel_spacer+(wheel_width/2)} ${wheel_radius}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="caster" is_caster="true" >
    <origin xyz="${fwheel_offset} 0 ${wheel_radius}" rpy="0 0 0" />
  </xacro:wheel>

  <link name="scanner">
    <visual>
      <geometry>
        <box size="${scanner_width} ${scanner_length} ${scanner_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black">
        <color rgba="0.5 0 0 1"/>
      </material>
    </visual>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1" />
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
    </inertial>
  </link>
  
  <joint name="base_to_scanner" type="fixed">
    <parent link="base_link"/>
    <child link="scanner"/>
    <origin xyz="${scanner_x_offset} 0  ${scanner_z_offset}" rpy="0 0 0"/>
  </joint>
  
</robot>
